# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20180305_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievement',
            old_name='decription',
            new_name='description',
        ),
    ]
