# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_auto_20180305_0928'),
        ('section', '0003_auto_20180305_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=512)),
                ('meta', models.ImageField(blank=True, null=True, upload_to='static/uploads/projects/images')),
                ('document', models.FileField(blank=True, null=True, upload_to='static/uploads/projects/documents')),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('ongoing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.Profile')),
            ],
        ),
    ]
