# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_auto_20180305_0928'),
        ('section', '0006_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('CON', 'Convener'), ('COC', 'Co-Convener'), ('TRE', 'Treaserer'), ('WEB', 'Web Team'), ('TEC', 'Tech Team'), ('DOC', 'Documentation Team'), ('DSG', 'Design Team'), ('RND', 'Research and Development Team'), ('EXE', 'Executive')], default='EXE', max_length=3)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_profile.Profile')),
            ],
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
    ]
