# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_auto_20180305_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.TextField(max_length=32)),
                ('description', models.TextField(max_length=256)),
                ('meta', models.ImageField(blank=True, null=True, upload_to='static/uploads/announcementes')),
                ('link', models.TextField(max_length=32)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Announcementes',
            },
        ),
    ]
