# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='meta',
            field=models.ImageField(blank=True, null=True, upload_to='static/uploads/announcements'),
        ),
    ]
