# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_profile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('STU', 'Student'), ('FAC', 'Faculty'), ('STF', 'Staff'), ('ALU', 'Alumni')], default='STU', max_length=3),
        ),
    ]
